version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - POST=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
